# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QGraphicsScene
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.backends.backend_qt5 import FigureCanvasQT
from matplotlib.backends.backend_template import FigureCanvas
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
from PyQt5.QtWidgets import QSizePolicy


from dataprocessing import list1, list2, list3, slist1, slist2, slist3

import matplotlib

matplotlib.use("Qt5Agg")
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


class Figure_Canvas1(FigureCanvas):
    # 通过继承FigureCanvas类，使得该类既是一个PyQt5的Qwidget，又是一个matplotlib的FigureCanvas，这是连接pyqt5与matplot                                          lib的关键

    def __init__(self, parent=None, width=4, height=3.9, dpi=100):
        fig = Figure(figsize=(width, height),
                     dpi=100)  # 创建一个Figure，注意：该Figure为matplotlib下的figure，不是matplotlib.pyplot下面的figure

        FigureCanvas.__init__(self, fig)  # 初始化父类
        self.setParent(parent)

        self.axes = fig.add_subplot(111)  # 调用figure下面的add_subplot方法，类似于matplotlib.pyplot下面的subplot方法

    def test(self):
        # x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
        # y = [23, 21, 32, 13, 3, 132, 13, 3, 1]
        x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        self.axes.plot(x, list1)





class Figure_Canvas2(FigureCanvas):
    # 通过继承FigureCanvas类，使得该类既是一个PyQt5的Qwidget，又是一个matplotlib的FigureCanvas，这是连接pyqt5与matplot                                          lib的关键

    def __init__(self, parent=None, width=4, height=3.9, dpi=100):
        fig = Figure(figsize=(width, height),
                     dpi=100)  # 创建一个Figure，注意：该Figure为matplotlib下的figure，不是matplotlib.pyplot下面的figure

        FigureCanvas.__init__(self, fig)  # 初始化父类
        self.setParent(parent)

        self.axes = fig.add_subplot(111)  # 调用figure下面的add_subplot方法，类似于matplotlib.pyplot下面的subplot方法

    def test(self):
        # x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
        # y = [23, 21, 32, 13, 3, 132, 13, 3, 1]
        x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        self.axes.plot(x, list2)


class Figure_Canvas3(FigureCanvas):
    # 通过继承FigureCanvas类，使得该类既是一个PyQt5的Qwidget，又是一个matplotlib的FigureCanvas，这是连接pyqt5与matplot                                          lib的关键

    def __init__(self, parent=None, width=4, height=3.9, dpi=100):
        fig = Figure(figsize=(width, height),
                     dpi=100)  # 创建一个Figure，注意：该Figure为matplotlib下的figure，不是matplotlib.pyplot下面的figure

        FigureCanvas.__init__(self, fig)  # 初始化父类
        self.setParent(parent)

        self.axes = fig.add_subplot(111)  # 调用figure下面的add_subplot方法，类似于matplotlib.pyplot下面的subplot方法

    def test(self):
        # x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
        # y = [23, 21, 32, 13, 3, 132, 13, 3, 1]
        x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        self.axes.plot(x, list3)


# print(list1)
# print(list2)
# print(list3)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(800, 600)
        MainWindow.resize(1025, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 320, 101, 51))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 80, 121, 41))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.setPlaceholderText("——请选择——")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 80, 151, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 200, 151, 41))
        self.label_2.setObjectName("label_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(200, 200, 121, 41))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.setPlaceholderText("——请选择——")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 440, 121, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 480, 131, 51))
        # self.pushButton_2.setGeometry(QtCore.QRect(500, 350, 131, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        # self.graphicsView.setGeometry(QtCore.QRect(450, 120, 250, 200))
        self.graphicsView.setGeometry(QtCore.QRect(450, 40, 500, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 440, 161, 51))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.comboBox_2.currentIndexChanged.connect(self.selectionchange1)
        self.comboBox_4.currentIndexChanged.connect(self.selectionchange2)
        self.pushButton.clicked.connect(self.pushButton_click)
        self.pushButton_2.clicked.connect(self.pushButton_2_click)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWindowTitle(_translate("MainWindow", "学习时间统计"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "10月"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "11月"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "12月"))
        self.label.setText(_translate("MainWindow", "请选择月份："))
        self.label_2.setText(_translate("MainWindow", "请选择姓名："))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "高林"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "黄信旭"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "宋宇星"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "汪磊"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "王若风"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "吴李览益"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "吴泽辉"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "杨华斌"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "余恩泽"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "余柔"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "张天天"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "张雨泉"))
        self.pushButton_2.setText(_translate("MainWindow", "显示当月图表"))
        self.label_3.setText(_translate("MainWindow", "该生本月学习时间为："))

    def selectionchange1(self, i):
        global m
        m = i
        # print(m)

    def selectionchange2(self, i):
        global n
        n = i
        # print(n)

    def pushButton_click(self):
        if m == 0 or m == 1 or m == 2:
            if m == 0:
                for i in range(12):
                    if n == i:
                        self.textBrowser.setText(slist1[i])
            if m == 1:
                for i in range(12):
                    if n == i:
                        self.textBrowser.setText(slist2[i])
            if m == 2:
                for i in range(12):
                    if n == i:
                        self.textBrowser.setText(slist3[i])
        else:
            self.textBrowser.setText("请选择月份")


    def pushButton_2_click(self):
        if m == 0:
            dr = Figure_Canvas1()
        if m == 1:
            dr = Figure_Canvas2()
        if m == 2:
            dr = Figure_Canvas3()
        dr.test()  # 画图
        graphicscene = QtWidgets.QGraphicsScene()  # 第三步，创建一个QGraphicsScene，因为加载的图形（FigureCanvas）不能直接放到graphicview控件中，必须先放到graphicScene，然后再把graphicscene放到graphicview中
        graphicscene.addWidget(dr)  # 第四步，把图形放到QGraphicsScene中，注意：图形是作为一个QWidget放到QGraphicsScene中的
        self.graphicsView.setScene(graphicscene)  # 第五步，把QGraphicsScene放入QGraphicsView
        self.graphicsView.show()  # 最后，调用show方法呈现图形！Voila!!
